remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

collections:
  mods:
    output: true
    permalink: /mods/:name/

defaults:
  - scope:
      path: ""
      type: mods
    values:
      layout: single
      author_profile: false
